
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: crw-operator-group
  namespace: crw
spec:
  targetNamespaces:
  - crw
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: codeready-workspaces
  namespace: crw
spec:
  channel: latest
  name: codeready-workspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace